# Generated by Django 5.1.5 on 2025-01-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shape",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shape_type",
                    models.CharField(
                        choices=[
                            ("circle", "Circle"),
                            ("triangle", "Triangle"),
                            ("square", "Square"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
